### ISSUE TITLE
Unable to install Rule Designer

### ISSUE THREAD

**Issue by piyabisht** [ODMDev/ruledesigner#5]
I'm trying to install rule designer through instructions mentioned. It is showing error and installation is failing.
Could anyone please assist.
Error is - Unable to read repository at https://raw.githubusercontent.com/ODMDev/ruledesigner/8.9.2/p2/content.xml

Regards,
Priya Bisht

**Comment by lgrateau** [comment]
What is the behavior you observe ?
Do you have some logs ?

**Comment by masterthefly** [comment]
is this fixed?  Is there a solution to install rule designer into eclipse successfully? This is the worst development experience one is having with RulesDesigner. None of the instructions in Readme document for getting this installed into eclipse is working. The URL links for rawgithubusercontent is throwing 404 errors and one cannot install rule designer plugin from eclipse market place even with running latest eclipse.

**Comment by lgrateau** [comment]
@masterthefly 
   * What is the ODM version would you like to install ?
I'm not aware issue regarding the installation. 
Could you provide me logs and how to reproduce steps to reproduce the issue ?
The simple way is to use the Eclispe marketplace.
  - Install an Eclipse version. See the  https://github.com/ODMDev/ruledesigner/ to have the list of supported eclipse version vs odm.
  - Open Eclipse and go to the market place install
  - Search ODM and select the version.
  - Then install

**Comment by masterthefly** [comment]
Tried to install on both the latest Eclipse 2020-03 version (Version: 2020-03 (4.15.0)
Build id: 20200313-1211 ) and also on Eclipse Luna (Version: Luna Service Release 2 (4.4.2) Build id: 20150219-0600)

With Eclipse latest 2020-03 version, its throwing (cannot install this solution on this version of eclipse), I tried to download/install Eclipse modelling tools and tried again, still same errors, not able to install any ODM version that is available in Eclipse Market place).

WIth Eclipse Luna - here are the errors:
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_221
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.equinox.p2.transport.ecf
Warning
Mon Apr 27 08:09:03 EDT 2020
Connection to https://raw.githubusercontent.com/ODMDev/ruledesigner/8.10.2/p2/p2.index failed on sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Retry attempt 0 started

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:750)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:159)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flush(AbstractSessionOutputBuffer.java:166)
	at org.apache.http.impl.AbstractHttpClientConnection.doFlush(AbstractHttpClientConnection.java:272)
	at org.apache.http.impl.AbstractHttpClientConnection.flush(AbstractHttpClientConnection.java:277)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.flush(AbstractClientConnAdapter.java:201)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:239)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1077)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1068)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1064)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 29 more

**Comment by lgrateau** [comment]
Hi,

I have install successfully the 8.10.2 on my machine. As mention in the [Requirement](https://github.com/ODMDev/ruledesigner#requirements) should be Oxygen for 8.10.2

 - Install https://www.eclipse.org/downloads/packages/release/oxygen/3a
 - Menu Help->Install New Software
 - Add https://raw.githubusercontent.com/ODMDev/ruledesigner/8.10.2/p2  repo
 - Install 

Let me know if it's work better with this step by step

**Comment by lgrateau** [comment]
No response since 7 days close this issue.
